project:
  type: website

website:
  title: "teatro para robots"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


quarto:
  markdown:
    extensions:
      - qmdcarousel

