---
title: "Cifo exam"
---

Este es simplemente un modelo de prueba para mostrar mi capacidad para utilizar los distintos recursos que ofrece Quarto, al tiempo que me sirve a mi como apuntes para el futuro 


::: {.callout-note}
Genera recuadros destacados. tiene estos 5 de base
`note`, `warning`, `important`, `tip`, y `caution`.
:::

::: {.column-margin}
Para escribir informacion al lateral
:::


::: {.callout-caution collapse="true"}
## Como hacer un callout que se expande

Para extender o esconder informacion dentro de un callout
:::

A continuación un primer esquema de como traducir metodologia SCRUM al proceso de creación teatral. Utilizando mermaid.

```{mermaid}
flowchart LR
  A[Idea del espectaculo] --> B(Problemas a resolver)
  B --> C{autoasignacion de tareas}
  C --> D[direccion / scrum master]
  C --> E[dramaturgia / product owner]
  C --> F[escenografia]
  C --> G[iluminacion]
  C --> H[sonido]
  C --> I[interpretacion]
  D --> J[puesta en escena]
  E --> J[puesta en escena]
  F --> J[puesta en escena]
  G --> J[puesta en escena]
  H --> J[puesta en escena]
  I --> J[puesta en escena]
  J --> k[representacion]
  k --> L[retrospectiva]
  L --> M[Nueva idea de espectaculo]
  M --> B
  
  ```


Un ejemplo de como importar codigo, y al tiempo ejemplo de como utilizar ojs.

```{ojs}
import {image} from "@mbostock/voronoi-stippling"
image
```

ejemplo de como crear lista de links con nombres:

 Marketing de contenidos: [uberflip](<https://www.uberflip.com/>)
- Generación de contenidos: [Articoolo](http://articoolo.com/)
- Generación de contenidos: [Buzzsumo](https://buzzsumo.com/)
- Generación de contenidos: [Jasper](https://www.jasper.ai/)
- Creación de contenidos: [Concured](https://concured.com/)